### ISSUE TITLE
Criação da página sobre

### ISSUE THREAD

**Issue by danilo-lc** [gilmar-mmj/github-master#3]
Vocês poderiam criar uma página sobre?Agradeço.

**Comment by gilmar-mmj** [comment]
A pagina ja esta em produção

**Comment by danilo-lc** [comment]
Obrigado, estou esperando.

Enviado do meu iPhone

Em 21 de jul de 2020, à(s) 23:31, Gilmar Margoti <notifications@github.com> escreveu:

﻿

A pagina ja esta em produção
